language: python
python:
  - "3.8"
# command to install dependencies
env:
  - APP_SETTINGS=config.TestConfig DATABASE_URL=sqlite:///test.db
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - nose2 -v
after_success:
  - bash <(curl -s https://codecov.io/bash)