version: '3.7'

services:
    fizzbuzzApi:
        build: .
        image: fizzbuzzapi
        ports:
            - 5000:5000
        environment:
            APP_SETTINGS: "config.ProductionConfig"
            DATABASE_URL: "postgresql://fzapiuser:jn45vrt5v23@db"
        depends_on:
            - db
            
    db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: fzapiuser
            POSTGRES_PASSWORD: jn45vrt5v23
        volumes:
            - ./Database/fizzbuzz.sql:/docker-entrypoint-initdb.d/init.sql